# Generated by Django 5.0 on 2023-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
