# Generated by Django 5.0 on 2023-12-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstore', '0003_alter_orders_ship_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
